ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "paymentDueDate" TIMESTAMP(3);
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3);
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "paymentReference" TEXT DEFAULT '';
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "paymentNotes" TEXT DEFAULT '';
